### PR TITLE
[To-Do] Enhancement of Features + Fixes in CSS and Responsiveness

### LINKED ISSUE #81: [To-Do] [Calendar] Sync To-Do List with Calendar
### Objectives
The goal of this issue is to be able to sync all the tasks being added to the to-do list to automatically be reflected onto the calendar module as well. This will allow our product to have encompass seamless integrations across all modules and link the code with each other. 

### Acceptance Criteria
- [x] `to-do` and `calendar` files are linked with each other
- [x] Changes made to a task on the to-do list and have a date set is displayed on the calendar widget too

### Assignees
- @kabirsachdev7 
- @shjucsd 
- @ChooChooChao

### LINKED ISSUE #108: [To-Do] Feature Enhancement
### Objectives
The objective of this issue to make minor changes in ToDo like fixing the category-select id issue, random title generation for newly created tasks, updating labels to have it consistent with calendar. 

### Acceptance Criteria
- [ ] Category-Select identical id issue resolved
- [ ] Random Title Generated correctly stored in localStorage and displayed
- [ ] New labels - Personal, Work, School, Other
- [ ] JSDoc comments for all functions

### Assignees
- @shjucsd 

### Additional Notes <Optional>
Potentially change color scheme of labels, make minor changes to font styles to make things stand out.

### PR DESCRIPTION
**Pull request by shjucsd**
# Objective
This PR is meant to tackle various issues which we were working on during the sprint.

### Solution
- [ ] JSdoc comments for all functions
- [ ] Responsiveness handled
- [ ] Updated CSS to align with UI
- [ ] Calendar syncs when new task created
- [ ] Updated labels and resolved the same id issue
- [ ] Random Title Generation for Tasks

### Assignees
- @shjucsd 
- @ChooChooChao 
- @alt012ucsd 

### Additional Notes <Optional>
Can still make more changes to CSS to make certain elements stand out

### CODE REVIEW

**Review by kabirsachdev7 — CHANGES_REQUESTED** [review]
Good stuff! just have some notes:
3 main things:
1. realign the label part
2. increase size of the white box since its hard to see from far
3. when u save the task the position of the label shifts 

image

image

**Comment by shjucsd** [comment]
Yeah, I think because the label right now is changing relatively to the title length. Will fix that and increase the size of the edit box.

**Comment by kabirsachdev7** [comment]
yes it is, sounds good. will approve after those commits

**Review by kabirsachdev7 — APPROVED** [review]
approved, thanks!

**Pull request merged**
