### PR TITLE
[Journal] Make NavBar UI look more consistent to other pages 

### PR DESCRIPTION
**Pull request by kennethkietvuong**
### Objectives
Change the CSS of the journal to make the navigation bar look more consistent with the other pages.

image

### Solution
- Modify `journal-style.css` & `journal-page.html` file to have similar navbar design
- Added JSdoc comments to a function in `journal-app.js`

### Assignees
- @kennethkietvuong 

### Additional Notes 
Journal doesn't have responsiveness support yet (not sure how to do it myself)

### CODE REVIEW

**Review by shjucsd — APPROVED** [review]
css appearing like this: 
image

**Comment by shjucsd** [comment]
Pushed change to add margin to the bottom of text

**Comment by shjucsd** [comment]
Technically, it is still not consistent as the height level of navbar is not same as other widgets. I approved it but we should ask about others thoughts on it.

**Review by adironene — APPROVED** [review]

**Review by ChooChooChao — APPROVED** [review]
I think it looks great! The navbar matches perfectly with the other pages.

**Review by kabirsachdev7 — CHANGES_REQUESTED** [review]
Need to fix the nav bar on calendar then we should be good to merge

**Review by kabirsachdev7 — APPROVED** [review]

**Pull request merged**
