### PR TITLE
Journal unit testing

### LINKED ISSUE #50: [Journal] Testing for Add
### Objectives
Add unit testing/E2E testing to be able to test the feature to add journals in the journal page

### Acceptance Criteria
- [x] Unit Testing / E2E Testing Configured for GitHub Actions
- [x] Create Jest/Puppeteer tests for testing the Add Journal Feature
- [ ] Tests automatically ran and checked using GitHub Actions

### Assignees
- @kennethkietvuong 
- @AliMohammadiasl 
- @shjucsd 
- @kabirsachdev7

### PR DESCRIPTION
**Pull request by AliMohammadiasl**
Added end 2 end tests 

- Test the functionality of the add button
- Test the functionality of the journal entry
- Test whether the journal entry saves the contents written within it

Closes #50

### CODE REVIEW

**Review by shjucsd — COMMENTED** [review]
I added another test for checking the number of entries in localStorage after page reload. Also when I try to run the tests, it shows preset not found.

image

**Comment by kennethkietvuong** [comment]
> I added another test for checking the number of entries in localStorage after page reload. Also when I try to run the tests, it shows preset not found.

It works for me! Did you install jest-puppeteer after pulling from the branch using `npm install --save-dev jest-puppeteer`?
image

**Review by kennethkietvuong — APPROVED** [review]
I looked at the tests and it looks good!

**Review by shjucsd — APPROVED** [review]
The previous comment was an issue from my side. It looks good!

**Review by adironene — APPROVED** [review]

**Pull request merged**
